In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Datasets/Training.csv")

In [3]:
df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [4]:
df.shape

(4920, 133)

In [5]:
df["prognosis"]

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...                   
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: prognosis, Length: 4920, dtype: object

In [6]:
df["prognosis"].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [7]:
len(df["prognosis"].unique())

41

Train Test Split

In [8]:
import sys
print(sys.executable)


c:\Python311\python.exe


In [9]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [10]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [11]:
le = LabelEncoder()
le.fit(y)
Y = le.transform(y)

In [12]:
x

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
0     ...                   0           0         0             0   
1     ...                   0           0         0             0   
2     ...                   0           0         0             0   
3     ...                   0           0         0             0   
4     ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
4915  ...                   0           0         0             0   
4916  ...                   1           1         1             0   
4917  ...                   0           0         0             0   
4918  ...                   0           0         0             1   
4919  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                       0                     0                   0        0   
1                       0                     0                   0        0   
2                       0                     0                   0        0   
3                       0                     0                   0        0   
4                       0                     0                   0        0   
...                   ...                   ...                 ...      ...   
4915                    0                     0                   0        0   
4916                    0                     0                   0        0   
4917                    0                     0                   0        0   
4918                    1                     1                   1        0   
4919                    0                     0                   0        1   

      red_sore_around_nose  yellow_crust_ooze  
0                        0                  0  
1                        0                  0  
2                        0                  0  
3                        0                  0  
4                        0                  0  
...                    ...                ...  
4915                     0                  0  
4916              

In [13]:
# here we are converting targert value ("Prognosis") to integer value (just like get_dummies)

In [14]:
for i in y:
  print(i)

Fungal infection
Fungal infection
Fungal infection
Fungal infection
Fungal infection
Fungal infection
Fungal infection
Fungal infection
Fungal infection
Fungal infection
Allergy
Allergy
Allergy
Allergy
Allergy
Allergy
Allergy
Allergy
Allergy
Allergy
GERD
GERD
GERD
GERD
GERD
GERD
GERD
GERD
GERD
GERD
Chronic cholestasis
Chronic cholestasis
Chronic cholestasis
Chronic cholestasis
Chronic cholestasis
Chronic cholestasis
Chronic cholestasis
Chronic cholestasis
Chronic cholestasis
Chronic cholestasis
Drug Reaction
Drug Reaction
Drug Reaction
Drug Reaction
Drug Reaction
Drug Reaction
Drug Reaction
Drug Reaction
Drug Reaction
Drug Reaction
Peptic ulcer diseae
Peptic ulcer diseae
Peptic ulcer diseae
Peptic ulcer diseae
Peptic ulcer diseae
Peptic ulcer diseae
Peptic ulcer diseae
Peptic ulcer diseae
Peptic ulcer diseae
Peptic ulcer diseae
AIDS
AIDS
AIDS
AIDS
AIDS
AIDS
AIDS
AIDS
AIDS
AIDS
Diabetes 
Diabetes 
Diabetes 
Diabetes 
Diabetes 
Diabetes 
Diabetes 
Diabetes 
Diabetes 
Diabetes 
Gastroente

In [15]:
for i,j in zip(y,Y):
  print(f" {i}  : {j}")

 Fungal infection  : 15
 Fungal infection  : 15
 Fungal infection  : 15
 Fungal infection  : 15
 Fungal infection  : 15
 Fungal infection  : 15
 Fungal infection  : 15
 Fungal infection  : 15
 Fungal infection  : 15
 Fungal infection  : 15
 Allergy  : 4
 Allergy  : 4
 Allergy  : 4
 Allergy  : 4
 Allergy  : 4
 Allergy  : 4
 Allergy  : 4
 Allergy  : 4
 Allergy  : 4
 Allergy  : 4
 GERD  : 16
 GERD  : 16
 GERD  : 16
 GERD  : 16
 GERD  : 16
 GERD  : 16
 GERD  : 16
 GERD  : 16
 GERD  : 16
 GERD  : 16
 Chronic cholestasis  : 9
 Chronic cholestasis  : 9
 Chronic cholestasis  : 9
 Chronic cholestasis  : 9
 Chronic cholestasis  : 9
 Chronic cholestasis  : 9
 Chronic cholestasis  : 9
 Chronic cholestasis  : 9
 Chronic cholestasis  : 9
 Chronic cholestasis  : 9
 Drug Reaction  : 14
 Drug Reaction  : 14
 Drug Reaction  : 14
 Drug Reaction  : 14
 Drug Reaction  : 14
 Drug Reaction  : 14
 Drug Reaction  : 14
 Drug Reaction  : 14
 Drug Reaction  : 14
 Drug Reaction  : 14
 Peptic ulcer diseae  : 33
 Pe

In [16]:
Y

array([15, 15, 15, ..., 38, 35, 27])

In [17]:
# x = df.drop("prognosis" ,axis = 1)                #axis equal to 1 means column wise   //    o means row wise (here we are dropping it column wise prognosis)
# y = df["prognosis"]

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x,Y,test_size=0.3 ,random_state = 42)

In [19]:
x_train

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
682         0          0                     0                    0   
3963        0          0                     0                    0   
3126        0          0                     0                    0   
4480        0          0                     0                    0   
3411        0          0                     0                    0   
...       ...        ...                   ...                  ...   
4426        0          1                     0                    0   
466         0          0                     0                    0   
3092        0          1                     0                    0   
3772        1          1                     1                    0   
860         1          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
682           0       1           0             0        0                 0   
3963          0       1           0             0        0                 0   
3126          0       0           0             0        0                 0   
4480          0       0           0             0        1                 0   
3411          0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4426          0       0           1             0        0                 0   
466           0       0           0             0        0                 0   
3092          0       1           1             0        0                 0   
3772          0       0           0             0        0                 0   
860           0       0           0             1        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
682   ...                   0           0         0             0   
3963  ...                   0           0         0             0   
3126  ...                   0           0         0             0   
4480  ...                   0           0         0             0   
3411  ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
4426  ...                   0           0         0             1   
466   ...                   0           0         0             0   
3092  ...                   0           0         0             0   
3772  ...                   0           0         0             0   
860   ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
682                     0                     0                   0        0   
3963                    0                     0                   0        0   
3126                    0                     0                   0        0   
4480                    0                     0                   0        0   
3411                    0                     0                   0        0   
...                   ...                   ...                 ...      ...   
4426                    1                     1                   1        0   
466                     0                     0                   0        0   
3092                    0                     0                   0        0   
3772                    0                     0                   0        0   
860                     0                     0                   0        0   

      red_sore_around_nose  yellow_crust_ooze  
682                      0                  0  
3963                     0                  0  
3126                     0                  0  
4480                     0                  0  
3411                     0                  0  
...                    ...                ...  
4426                     0                  0  
466               

In [20]:
x_test

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
373         0          1                     0                    0   
4916        0          1                     0                    0   
1550        0          0                     0                    0   
3081        0          0                     0                    0   
3857        1          0                     0                    0   
...       ...        ...                   ...                  ...   
3649        1          1                     1                    0   
1694        0          0                     0                    0   
4767        0          0                     0                    0   
3721        0          0                     0                    0   
2222        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
373           0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
1550          0       0           0             0        0                 0   
3081          0       0           0             0        0                 0   
3857          0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
3649          0       0           0             0        0                 0   
1694          0       0           0             0        0                 0   
4767          0       0           0             0        1                 0   
3721          0       0           0             0        0                 0   
2222          0       1           1             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
373   ...                   0           1         1             0   
4916  ...                   1           1         1             0   
1550  ...                   0           0         0             0   
3081  ...                   0           0         0             0   
3857  ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
3649  ...                   0           0         0             0   
1694  ...                   0           0         0             0   
4767  ...                   0           0         0             0   
3721  ...                   0           0         0             0   
2222  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
373                     0                     0                   0        0   
4916                    0                     0                   0        0   
1550                    0                     0                   0        0   
3081                    0                     0                   0        0   
3857                    0                     0                   0        0   
...                   ...                   ...                 ...      ...   
3649                    0                     0                   0        0   
1694                    0                     0                   0        0   
4767                    0                     0                   0        0   
3721                    0                     0                   0        0   
2222                    0                     0                   0        0   

      red_sore_around_nose  yellow_crust_ooze  
373                      0                  0  
4916                     0                  0  
1550                     0                  0  
3081                     0                  0  
3857                     0                  0  
...                    ...                ...  
3649                     0                  0  
1694              

In [21]:
for value in y_test:
    print(value)

2
2
24
1
9
23
25
5
19
30
38
12
21
35
3
3
13
22
12
7
6
40
19
6
4
20
34
30
26
30
9
19
17
22
39
30
28
14
34
38
20
0
23
12
28
17
25
19
35
35
18
36
39
4
24
20
37
10
38
33
25
24
36
18
0
26
32
1
0
13
15
6
2
22
26
9
27
27
10
30
16
27
16
14
19
1
28
17
0
11
26
29
21
3
36
17
29
18
34
11
23
6
3
4
33
39
16
30
22
1
21
39
18
25
12
14
26
28
25
3
7
35
32
8
5
34
17
24
35
31
11
7
7
7
9
2
19
34
13
37
33
18
35
19
21
31
14
39
36
3
12
31
33
37
23
37
25
21
3
4
6
28
1
18
40
37
29
6
27
24
40
21
40
17
34
27
1
40
10
8
29
1
4
40
30
37
12
19
11
38
37
2
39
34
22
8
15
7
19
31
17
40
39
11
15
0
16
4
9
8
19
31
18
13
17
28
29
18
9
21
11
3
3
23
32
40
8
17
26
35
5
13
37
34
35
14
31
6
12
5
10
20
4
39
32
36
36
9
32
18
19
22
13
11
27
34
13
10
10
1
18
10
10
14
0
26
10
8
13
25
26
5
29
37
26
16
30
27
34
1
37
24
40
35
24
33
6
36
12
33
16
11
22
40
15
11
19
14
1
15
36
6
27
22
35
19
23
31
16
32
20
15
33
1
25
7
6
20
13
15
40
22
30
16
38
30
23
1
6
37
11
5
38
19
21
24
10
3
16
2
20
11
35
2
4
1
16
17
3
40
11
6
29
21
38
12
31
39
14
27
40


In [22]:
x_train.shape ,x_test.shape ,y_train.shape ,y_test.shape

((3444, 132), (1476, 132), (3444,), (1476,))

Training the Model

In [23]:
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB


from sklearn.metrics import accuracy_score,confusion_matrix
import numpy as np


# Create a Dictionary
models = {
    "SVC" : SVC(kernel="linear"),
    "RandomForest":RandomForestClassifier(n_estimators=100,random_state = 42),
    "GradientBoosting":GradientBoostingClassifier(n_estimators=100,random_state=42),
    "KNeighbors":KNeighborsClassifier(n_neighbors=5),
    "MultiNomialNB":MultinomialNB()
}


for model_name , model in models.items():                    #here item gives 2 output (keys and value) used in dictionary
  # print(model , ": ", model_name)

  #train model
  model.fit(x_train,y_train)

  #model Prediction
  y_pred = model.predict(x_test)

  #Calculate Accuracy
  accuracy = accuracy_score(y_test,y_pred)

  # Calculate confusion Matrix
  cm = confusion_matrix(y_test,y_pred)

  print(f"{model_name} accuracy : {accuracy}")
  print(f"{model_name} confusion matrix : {cm}")



SVC accuracy : 1.0
SVC confusion matrix : [[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]
RandomForest accuracy : 1.0
RandomForest confusion matrix : [[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]
GradientBoosting accuracy : 1.0
GradientBoosting confusion matrix : [[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]
KNeighbors accuracy : 1.0
KNeighbors confusion matrix : [[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 37  0]
 [ 0  0  0 ...  0  0 39]]
MultiNomialNB accuracy : 1.0
MultiNomialNB confusion matrix : [[32  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 41 ...  0  0  0]
 ...
 [ 0  0 

Single Prediction

In [24]:
# selecting svc
svc = SVC(kernel='linear')
svc.fit(x_train,y_train)
ypred = svc.predict(x_test)
accuracy_score(y_test,ypred)

1.0

In [25]:
# save svc
import pickle
pickle.dump(svc,open('svc.pkl','wb'))

In [26]:
# load model
svc = pickle.load(open('svc.pkl','rb'))

In [27]:
print("predicted disease :", svc.predict(x_test.iloc[100].values.reshape(1, -1)))
print("Actual Disease :", y_test[100])

predicted disease : [23]
Actual Disease : 23


c:\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [28]:
print("predicted disease :", svc.predict(x_test.iloc[10].values.reshape(1, -1)))
print("Actual Disease :", y_test[10])

predicted disease : [38]
Actual Disease : 38


c:\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [30]:
sym_des = pd.read_csv("Datasets/symtoms_df.csv")
precaution_s = pd.read_csv("Datasets/precautions_df.csv")
workout = pd.read_csv("Datasets/workout_df.csv")
description = pd.read_csv("Datasets/description.csv")
medication = pd.read_csv("Datasets/medications.csv")
diets = pd.read_csv("Datasets/diets.csv")


In [31]:
precaution_s

Unnamed: 0                                  Disease  \
0            0                            Drug Reaction   
1            1                                  Malaria   
2            2                                  Allergy   
3            3                           Hypothyroidism   
4            4                                Psoriasis   
5            5                                     GERD   
6            6                      Chronic cholestasis   
7            7                              hepatitis A   
8            8                          Osteoarthristis   
9            9  (vertigo) Paroymsal  Positional Vertigo   
10          10                             Hypoglycemia   
11          11                                     Acne   
12          12                                Diabetes    
13          13                                 Impetigo   
14          14                            Hypertension    
15          15                      Peptic ulcer diseae   
16          16             Dimorphic hemmorhoids(piles)   
17          17                              Common Cold   
18          18                              Chicken pox   
19          19                     Cervical spondylosis   
20          20                          Hyperthyroidism   
21          21                  Urinary tract infection   
22          22                           Varicose veins   
23          23                                     AIDS   
24          24             Paralysis (brain hemorrhage)   
25          25                                  Typhoid   
26          26                              Hepatitis B   
27          27                         Fungal infection   
28          28                              Hepatitis C   
29          29                                 Migraine   
30          30                         Bronchial Asthma   
31          31                      Alcoholic hepatitis   
32          32                                 Jaundice   
33          33                              Hepatitis E   
34          34                                   Dengue   
35          35                              Hepatitis D   
36          36                             Heart attack   
37          37                                Pneumonia   
38          38                                Arthritis   
39          39                          Gastroenteritis   
40          40                             Tuberculosis   

                            Precaution_1                        Precaution_2  \
0                        stop irritation            consult nearest hospital   
1               Consult nearest hospital                     avoid oily food   
2                         apply calamine             cover area with bandage   
3                          reduce stress                            exercise   
4       wash hands with warm soapy water        stop bleeding using pressure   
5                 avoid fatty spicy food       avoid lying down after eating   
6                             cold baths                  anti itch medicine   
7               Consult nearest hospital                  wash hands through   
8                          acetaminophen            consult nearest hospital   
9                               lie down         avoid sudden change in body   
10                      lie down on side                      check in pulse   
11                            bath twice              avoid fatty spicy food   
12                    have balanced diet                            exercise   
13      soak affected area in warm water                     use antibiotics   
14                            meditation                          salt baths   
15                avoid fatty spicy food              consume probiotic food   
16                avoid fatty spicy food                 consume witch hazel   
17           drink vitamin c rich drinks                         take vapour   
18   

In [32]:
medication.head()

Disease                                         Medication
0     Fungal infection  ['Antifungal Cream', 'Fluconazole', 'Terbinafi...
1              Allergy  ['Antihistamines', 'Decongestants', 'Epinephri...
2                 GERD  ['Proton Pump Inhibitors (PPIs)', 'H2 Blockers...
3  Chronic cholestasis  ['Ursodeoxycholic acid', 'Cholestyramine', 'Me...
4        Drug Reaction  ['Antihistamines', 'Epinephrine', 'Corticoster...

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
symptoms_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
diseases_list = {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}


# Model Prediction function
def get_predicted_value(patient_symptoms):
    input_vector = np.zeros(len(symptoms_dict))         # input_vector contains 132 zeros value
    for item in patient_symptoms:
        input_vector[symptoms_dict[item]] = 1
    return diseases_list[svc.predict([input_vector])[0]]

Test 1

In [36]:
#Test 1
symtoms = input("enter the patient symptoms")
input_symptoms = [s.strip() for s in symtoms.split(',')]
print(input_symptoms)

['chills', 'shivering']


In [37]:
get_predicted_value(input_symptoms)

c:\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


'Allergy'

Test 2    (used as disease Predict)


In [38]:
 # Handle NaN values - replace them with a placeholder string
precaution_s = precaution_s.fillna('No specific precaution')

In [41]:
def helper(dis):

    print("=================predicted disease============")
    print(dis)


    for i in range(len(description["Disease"])):
      if(description["Disease"][i] == dis):
        o =[ description['Description'][i]]
        desc_list = " ".join (o)



    for i in range(len(precaution_s)):
      # Check if the disease matches
      if precaution_s['Disease'][i] == disease_predict:
              # Access multiple precautions for the matching disease
              precautions_list = precaution_s.loc[i, ['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']]
              # Create a string from the list of precautions
              precaution_string = ", ".join(precautions_list)




    for i in range(len(diets)):
      if(diets["Disease"][i] == dis):
        diets_list = [diets["Diet"][i]]
        diets_list = ", ".join(diets_list)




    for i in range(len(medication)):
      if(medication["Disease"][i] == dis):
        medication_list = [medication["Medication"][i]]
        medication_list = ", ".join(medication_list)



    print("=================description==================")
    print(desc_list)



    print("=================precautions==================")
    b = precaution_string.split(",")
    i = 1
    for p_i in b:
      print(i, ": ", p_i)
      i += 1



    print("=================diets==================")
    c = diets_list.split(",")
    for d_i in c:
      print(i, ": ", d_i)
      i += 1


    print("=================medications==================")
    d = medication_list.split(",")
    for m_i in d:
      print(i, ": ", m_i)
      i += 1





In [42]:
#Test 2
symtoms = input("enter the patient symptoms")
input_symptoms_2 = [s.strip() for s in symtoms.split(',')]
print(input_symptoms_2)

['skin_rash', 'stomach_pain']


In [43]:
disease_predict = get_predicted_value(input_symptoms_2)
disease_predict

c:\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


'Drug Reaction'

In [44]:
helper(disease_predict)

=================predicted disease============
Drug Reaction
=================description==================
Drug Reaction occurs when the body reacts adversely to a medication.
=================precautions==================
1 :  stop irritation
2 :   consult nearest hospital
3 :   stop taking drug
4 :   follow up
=================diets==================
5 :  ['Antihistamine Diet'
6 :   'Omega-3-rich foods'
7 :   'Vitamin C-rich foods'
8 :   'Quercetin-rich foods'
9 :   'Probiotics']
=================medications==================
10 :  ['Antihistamines'
11 :   'Epinephrine'
12 :   'Corticosteroids'
13 :   'Antibiotics'
14 :   'Antifungal Cream']


Simply trying to extract data of drug reaction using table


In [45]:
medication[medication["Disease"]=="Drug Reaction"]["Medication"]

4    ['Antihistamines', 'Epinephrine', 'Corticoster...
Name: Medication, dtype: object

In [46]:
medication

Disease  \
0                         Fungal infection   
1                                  Allergy   
2                                     GERD   
3                      Chronic cholestasis   
4                            Drug Reaction   
5                     Peptic ulcer disease   
6                                     AIDS   
7                                 Diabetes   
8                          Gastroenteritis   
9                         Bronchial Asthma   
10                            Hypertension   
11                                Migraine   
12                    Cervical spondylosis   
13            Paralysis (brain hemorrhage)   
14                                Jaundice   
15                                 Malaria   
16                             Chicken pox   
17                                  Dengue   
18                                 Typhoid   
19                             hepatitis A   
20                             Hepatitis B   
21                             Hepatitis C   
22                             Hepatitis D   
23                             Hepatitis E   
24                     Alcoholic hepatitis   
25                            Tuberculosis   
26                             Common Cold   
27                               Pneumonia   
28            Dimorphic hemmorhoids(piles)   
29                            Heart attack   
30                          Varicose veins   
31                          Hypothyroidism   
32                         Hyperthyroidism   
33                            Hypoglycemia   
34                         Osteoarthristis   
35                               Arthritis   
36  (vertigo) Paroymsal Positional Vertigo   
37                                    Acne   
38                 Urinary tract infection   
39                               Psoriasis   
40                                Impetigo   

                                           Medication  
0   ['Antifungal Cream', 'Fluconazole', 'Terbinafi...  
1   ['Antihistamines', 'Decongestants', 'Epinephri...  
2   ['Proton Pump Inhibitors (PPIs)', 'H2 Blockers...  
3   ['Ursodeoxycholic acid', 'Cholestyramine', 'Me...  
4   ['Antihistamines', 'Epinephrine', 'Corticoster...  
5   ['Antibiotics', 'Proton Pump Inhibitors (PPIs)...  
6   ['Antiretroviral drugs', 'Protease inhibitors'...  
7   ['Insulin', 'Metformin', 'Sulfonylureas', 'DPP...  
8   ['Antibiotics', 'Antiemetic drugs', 'Antidiarr...  
9   ['Bronchodilators', 'Inhaled corticosteroids',...  
10  ['Antihypertensive medications', 'Diuretics', ...  
11  ['Analgesics', 'Triptans', 'Ergotamine derivat...  
12  ['Pain relievers', 'Muscle relaxants', 'Physic...  
13  ['Blood thinners', 'Clot-dissolving medication...  
14  ['IV fluids', 'Blood transfusions', 'Liver tra...  
15  ['Antimalarial drugs', 'Antipyretics', 'Antiem...  
16  ['Antiviral drugs', 'Pain relievers', 'IV flui...  
17  ['Antibiotics', 'Antipyretics', 'Analgesics', ...  
18  ['Vaccination', 'Antiviral drugs', 'IV fluids'...  
19  ['Vaccination', 'Antiviral drugs', 'IV fluids'...  
20  ['Antiviral drugs', 'IV fluids', 'Blood transf...  
21  ['Antiviral drugs', 'IV fluids', 'Blood transf...  
22  ['Antiviral drugs', 'IV fluids', 'Blood transf...  
23  ['Alcohol cessation', 'Corticosteroids', 'IV f...  
24  ['Antibiotics', 'Isoniazid', 'Rifampin', 'Etha...  
25  ['Antipyretics', 'Decongestants', 'Cough suppr...  
26  ['Antibiotics', 'Antiviral drugs', 'Antifungal...  
27  ['Laxatives', 'Pain relievers', 'Warm baths', ...  
28  ['Nitroglycerin', 'Aspirin', 'Beta-blockers', ...  
29  ['Compression stockings', 'Exercise', 'Elevati...  
30  ['Levothyroxine', 'Antithyroid medications', '...  
31  ['Antithyroid medications', 'Radioactive iodin...  
32  ['Glucose tablets', 'Candy or juice', 'Glucago...  
33  ['Pain relievers', 'Exercise', 'Hot and cold p...  
34  ['NSAIDs', 'Disease-modifying antirheumatic dr...  
35  ['Vestibular rehabilitation', 'Canalith reposi...  
36  ['Topical treatments', 'An